[dependencies]
starknet = "2.4.3"

[dependencies.snforge_std]
git = "https://github.com/foundry-rs/starknet-foundry"
tag = "v0.13.1"

[package]
edition = "2023_10"
name = "storage"
version = "0.1.0"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.sncast]
account = "account1"
accounts-file = "/home/kayzee/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:5050/rpc"
